
from enum import StrEnum
class ErrorCode(StrEnum):

    # Common
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    # Users
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS"
    USER_INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS"
    USER_EMAIL_NOT_VERIFIED = "USER_EMAIL_NOT_VERIFIED"

    # Products
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_SKU_ALREADY_EXISTS = "PRODUCT_SKU_ALREADY_EXISTS"
    PRODUCT_OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK"

    # Orders
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_INVALID_STATUS = "ORDER_INVALID_STATUS"
    ORDER_ITEM_INVALID = "ORDER_ITEM_INVALID"

    # Categories
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    CATEGORY_NAME_ALREADY_EXISTS = "CATEGORY_NAME_ALREADY_EXISTS"

    # Images
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
    IMAGE_INVALID_FORMAT = "IMAGE_INVALID_FORMAT"