"""add categories and modify models

Revision ID: 71a6f7b09edb
Revises: c9d7e3a4b2f1
Create Date: 2026-06-04 20:11:38.581797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71a6f7b09edb'
down_revision: Union[str, None] = 'c9d7e3a4b2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('idx_order_items_status_id', table_name='order_items')
    op.drop_constraint('order_items_status_id_fkey', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'status_id')
    op.add_column('orders', sa.Column('status_code', sa.Integer(), nullable=False))
    op.drop_index('idx_orders_status_id', table_name='orders')
    op.create_index('idx_orders_status_code', 'orders', ['status_code'], unique=False)
    op.drop_constraint('orders_status_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'statuses', ['status_code'], ['code'])
    op.drop_column('orders', 'status_id')
    op.add_column('products', sa.Column('status_code', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=False))
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_status_id', table_name='products')
    op.create_index('idx_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('idx_products_status_code', 'products', ['status_code'], unique=False)
    op.drop_constraint('products_status_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'statuses', ['status_code'], ['code'])
    op.drop_column('products', 'image')
    op.drop_column('products', 'category')
    op.drop_column('products', 'status_id')
    op.drop_column('products', 'image_group')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.add_column('users', sa.Column('status_code', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('role_code', sa.Integer(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::timestamptz',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::timestamptz',
               existing_nullable=False)
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_index('idx_users_status_id', table_name='users')
    op.create_index('idx_users_role_code', 'users', ['role_code'], unique=False)
    op.create_index('idx_users_status_code', 'users', ['status_code'], unique=False)
    op.drop_constraint('users_status_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_code'], ['code'])
    op.create_foreign_key(None, 'users', 'statuses', ['status_code'], ['code'])
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('users_status_id_fkey', 'users', 'statuses', ['status_id'], ['id'])
    op.drop_index('idx_users_status_code', table_name='users')
    op.drop_index('idx_users_role_code', table_name='users')
    op.create_index('idx_users_status_id', 'users', ['status_id'], unique=False)
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('users', 'role_code')
    op.drop_column('users', 'status_code')
    op.add_column('roles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_group', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_status_id_fkey', 'products', 'statuses', ['status_id'], ['id'])
    op.drop_index('idx_products_status_code', table_name='products')
    op.drop_index('idx_products_category_id', table_name='products')
    op.create_index('idx_products_status_id', 'products', ['status_id'], unique=False)
    op.create_index('idx_products_category', 'products', ['category'], unique=False)
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'status_code')
    op.add_column('orders', sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_status_id_fkey', 'orders', 'statuses', ['status_id'], ['id'])
    op.drop_index('idx_orders_status_code', table_name='orders')
    op.create_index('idx_orders_status_id', 'orders', ['status_id'], unique=False)
    op.drop_column('orders', 'status_code')
    op.add_column('order_items', sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('order_items_status_id_fkey', 'order_items', 'statuses', ['status_id'], ['id'])
    op.create_index('idx_order_items_status_id', 'order_items', ['status_id'], unique=False)
    op.drop_table('categories')
    # ### end Alembic commands ###
