"""add product image and image_group

Revision ID: 7f20da8282f8
Revises: b32b13bd7b07
Create Date: 2026-06-01 20:13:24.618064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f20da8282f8'
down_revision: Union[str, None] = 'b32b13bd7b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(length=300), nullable=True))
    op.add_column('products', sa.Column('image_group', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_group')
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
