"""add auth email templates table

Revision ID: g4d9e3b1c6a27
Revises: f3c8e2a1d5b6
Create Date: 2026-06-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'g4d9e3b1c6a27'
down_revision: Union[str, None] = 'f3c8e2a1d5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_email_templates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('template_type', sa.Integer(), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_email_templates')
    # ### end Alembic commands ###
